import connectToDatabase from "../lib/mongodb";
import { Category } from "../lib/models/Category";
import { Product } from "../lib/models/Product";

const categorySeeds = [
  {
    slug: "smartphones",
    name: "Smartphones",
    description: "Latest authentic smartphones and mobile devices from top brands.",
    sortOrder: 1,
  },
  {
    slug: "audio",
    name: "Audio",
    description: "Premium wireless earbuds, headphones, and portable speakers.",
    sortOrder: 2,
  },
  {
    slug: "wearables",
    name: "Wearables",
    description: "Smartwatches, fitness trackers, and connected wrist gear.",
    sortOrder: 3,
  },
  {
    slug: "accessories",
    name: "Accessories",
    description: "Original chargers, fast-charging cables, protective cases, and power accessories.",
    sortOrder: 4,
  },
  {
    slug: "smart-home",
    name: "Smart Home",
    description: "Smart lighting, home security cameras, air purifiers, and streaming devices.",
    sortOrder: 5,
  },
];

const productSeeds = [
  // ── CATEGORY: SMARTPHONES (15 Items) ────────────────────────
  {
    slug: "apple-iphone-15-pro-max",
    name: "Apple iPhone 15 Pro Max (256GB)",
    categorySlug: "smartphones",
    price: 154990,
    compareAtPrice: 165000,
    shortDescription: "Flagship iPhone with aerospace-grade titanium design, A17 Pro chip, and 5x Telephoto camera.",
    description: "The Apple iPhone 15 Pro Max features a strong and light titanium design. It is powered by the groundbreaking A17 Pro chip, has a customizable Action button, and features the most advanced camera system in an iPhone yet.",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=600&auto=format&fit=crop",
    badge: "Best Seller",
    featured: true,
    inStock: true,
    sku: "YMS-PHN-AP15PM",
    specs: ["256GB NVMe Storage", "A17 Pro 3nm Processor", "6.7\" Super Retina XDR display", "48MP Triple Camera system", "Aerospace-grade Titanium Frame"],
  },
  {
    slug: "apple-iphone-15-128gb",
    name: "Apple iPhone 15 (128GB)",
    categorySlug: "smartphones",
    price: 98500,
    compareAtPrice: 105000,
    shortDescription: "Features the Dynamic Island, 48MP main camera, and durable color-infused glass design.",
    description: "The iPhone 15 brings you the Dynamic Island, a 48MP Main camera, and USB-C, all in a durable color-infused glass and aluminum design.",
    image: "/assets/product-smartphone.png",
    badge: "Popular",
    featured: false,
    inStock: true,
    sku: "YMS-PHN-AP15",
    specs: ["128GB Storage", "A16 Bionic Chip", "6.1\" Super Retina XDR display", "48MP Dual Camera system", "USB-C Port"],
  },
  {
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra (256GB)",
    categorySlug: "smartphones",
    price: 135000,
    compareAtPrice: 142000,
    shortDescription: "Flagship Android smartphone featuring Galaxy AI, Snapdragon 8 Gen 3, and Titanium frame.",
    description: "Meet the Galaxy S24 Ultra, the ultimate form of Galaxy Ultra with a new titanium exterior and a 6.8-inch flat screen. Packed with industry-leading Galaxy AI features like Live Translate, Circle to Search, and Photo Assist.",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=600&auto=format&fit=crop",
    badge: "Flagship",
    featured: true,
    inStock: true,
    sku: "YMS-PHN-SS24U",
    specs: ["256GB UFS 4.0 Storage", "Snapdragon 8 Gen 3 for Galaxy", "6.8\" Dynamic AMOLED 2X display", "200MP Quad Camera with 5x optical zoom", "Integrated S Pen"],
  },
  {
    slug: "samsung-galaxy-s24-plus",
    name: "Samsung Galaxy S24+ (256GB)",
    categorySlug: "smartphones",
    price: 112000,
    compareAtPrice: 118000,
    shortDescription: "Premium performance with QHD+ screen, Galaxy AI, and long-lasting 4900mAh battery.",
    description: "The Galaxy S24+ offers a gorgeous 6.7-inch QHD+ display, advanced Galaxy AI tools, a premium aluminum body, and an upgraded camera sensor setup for vibrant shots.",
    image: "/assets/product-smartphone.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-PHN-SS24P",
    specs: ["256GB Storage", "Exynos 2400 / Snapdragon 8 Gen 3", "6.7\" QHD+ Dynamic AMOLED 2X", "50MP Triple Camera", "4900mAh Battery"],
  },
  {
    slug: "samsung-galaxy-a55-5g",
    name: "Samsung Galaxy A55 5G (8GB/256GB)",
    categorySlug: "smartphones",
    price: 48500,
    compareAtPrice: 52000,
    shortDescription: "Premium mid-range phone with metal frame, 120Hz display, and IP67 rating.",
    description: "The Galaxy A55 5G features a premium glass back, metal frame, a fast Exynos 1480 processor, and a gorgeous 120Hz AMOLED display for everyday speed and style.",
    image: "/assets/product-smartphone.png",
    badge: "Hot Deal",
    featured: true,
    inStock: true,
    sku: "YMS-PHN-SA55",
    specs: ["8GB RAM / 256GB Storage", "Exynos 1480 Octa-core", "6.6\" Super AMOLED 120Hz", "50MP Triple Camera with OIS", "IP67 Dust & Water Resistant"],
  },
  {
    slug: "oneplus-12-512gb",
    name: "OnePlus 12 (16GB/512GB)",
    categorySlug: "smartphones",
    price: 92000,
    compareAtPrice: 98000,
    shortDescription: "High-performance smartphone with Snapdragon 8 Gen 3, Hasselblad cameras, and 100W charging.",
    description: "Redefined flagship. The OnePlus 12 combines Snapdragon 8 Gen 3 with a 4th Gen Hasselblad Camera System, 100W SUPERVOOC charging, and a ultra-bright 4500 nits display.",
    image: "/assets/product-smartphone.png",
    badge: "Featured",
    featured: true,
    inStock: true,
    sku: "YMS-PHN-OP12",
    specs: ["16GB LPDDR5X RAM", "512GB UFS 4.0 Storage", "6.82\" 2K Oriental AMOLED 120Hz", "50MP+64MP+48MP Hasselblad Camera", "100W Wired / 50W Wireless Charging"],
  },
  {
    slug: "oneplus-nord-ce4-256gb",
    name: "OnePlus Nord CE 4 (8GB/256GB)",
    categorySlug: "smartphones",
    price: 34500,
    compareAtPrice: 37000,
    shortDescription: "Balanced budget-mid-range smartphone with 100W SuperVOOC charging and Snapdragon 7 Gen 3.",
    description: "Powering the Nord range with a high-capacity 5500mAh battery, 100W charging, and Snapdragon 7 Gen 3 performance for effortless multitasking.",
    image: "/assets/product-smartphone.png",
    badge: "New Arrival",
    featured: false,
    inStock: true,
    sku: "YMS-PHN-OPNCE4",
    specs: ["8GB RAM / 256GB Storage", "Snapdragon 7 Gen 3", "6.7\" Fluid AMOLED 120Hz", "50MP Dual Camera", "5500mAh battery with 100W fast charge"],
  },
  {
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro (128GB)",
    categorySlug: "smartphones",
    price: 96500,
    compareAtPrice: 102000,
    shortDescription: "Google flagship with Tensor G3 chip, advanced AI cameras, and temperature sensor.",
    description: "The Google Pixel 8 Pro is the all-pro phone engineered by Google. It has the Google Tensor G3 chip, advanced photo and video editing capabilities, and a fully upgraded camera setup.",
    image: "/assets/product-smartphone.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-PHN-GP8P",
    specs: ["128GB UFS 3.1 Storage", "Google Tensor G3 (4nm)", "6.7\" LTPO OLED 120Hz Display", "50MP+48MP+48MP Camera system", "7 Years of Android updates support"],
  },
  {
    slug: "google-pixel-8a",
    name: "Google Pixel 8a (128GB)",
    categorySlug: "smartphones",
    price: 62000,
    compareAtPrice: 66000,
    shortDescription: "The AI-packed Google smartphone at an accessible price point, powered by Tensor G3.",
    description: "Pixel 8a is the smart, fast phone from Google, bringing high-end Pixel AI photography and features to a more budget-friendly design.",
    image: "/assets/product-smartphone.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-PHN-GP8A",
    specs: ["128GB Storage", "Google Tensor G3", "6.1\" OLED 120Hz display", "64MP + 13MP Dual Camera", "IP67 rating"],
  },
  {
    slug: "xiaomi-14-512gb",
    name: "Xiaomi 14 (12GB/512GB)",
    categorySlug: "smartphones",
    price: 86500,
    compareAtPrice: 92000,
    shortDescription: "Compact flagship with Leica professional optical lenses and Snapdragon 8 Gen 3.",
    description: "A compact marvel featuring a 6.36-inch display, a Leica Summilux lens system, Snapdragon 8 Gen 3 processor, and Xiaomi HyperOS for snappy performance.",
    image: "/assets/product-smartphone.png",
    badge: "Leica Lens",
    featured: false,
    inStock: true,
    sku: "YMS-PHN-XM14",
    specs: ["12GB RAM / 512GB Storage", "Snapdragon 8 Gen 3", "6.36\" LTPO OLED 120Hz", "50MP Leica Triple Camera", "90W Wired / 50W Wireless Charging"],
  },
  {
    slug: "redmi-note-13-pro-5g",
    name: "Redmi Note 13 Pro 5G (8GB/256GB)",
    categorySlug: "smartphones",
    price: 32500,
    compareAtPrice: 35000,
    shortDescription: "Features a massive 200MP camera, 1.5K 120Hz AMOLED display, and 67W Turbo charging.",
    description: "The Redmi Note 13 Pro 5G brings flagship specs to the mid-range with a high-resolution 200MP camera, Snapdragon 7s Gen 2 chip, and an ultra-thin bezel 1.5K screen.",
    image: "/assets/product-smartphone.png",
    badge: "Best Seller",
    featured: true,
    inStock: true,
    sku: "YMS-PHN-RN13P",
    specs: ["8GB RAM / 256GB Storage", "Snapdragon 7s Gen 2 (4nm)", "6.67\" 1.5K AMOLED 120Hz", "200MP Camera with OIS", "67W Turbo Charge"],
  },
  {
    slug: "poco-x6-pro-512gb",
    name: "Poco X6 Pro (12GB/512GB)",
    categorySlug: "smartphones",
    price: 37500,
    compareAtPrice: 40000,
    shortDescription: "Ultimate budget gaming phone with Dimensity 8300-Ultra and LPDDR5X + UFS 4.0 storage.",
    description: "Built for speed. The Poco X6 Pro is powered by the Dimensity 8300-Ultra processor, achieving top-tier gaming performance and a crystal-clear 120Hz AMOLED panel.",
    image: "/assets/product-smartphone.png",
    badge: "Gamer's Choice",
    featured: false,
    inStock: true,
    sku: "YMS-PHN-POCOX6P",
    specs: ["12GB RAM / 512GB UFS 4.0", "Dimensity 8300-Ultra (4nm)", "6.67\" AMOLED 120Hz", "64MP Triple Camera", "5000mAh with 67W Charger"],
  },
  {
    slug: "realme-gt-6-256gb",
    name: "Realme GT 6 (12GB/256GB)",
    categorySlug: "smartphones",
    price: 54000,
    compareAtPrice: 58000,
    shortDescription: "Flagship killer with Snapdragon 8s Gen 3, Next AI, and 120W SuperVOOC charge.",
    description: "The Realme GT 6 is packed with flagship-grade performance, featuring the Snapdragon 8s Gen 3, AI Smart Loop tools, a Sony LYT-808 primary camera, and dual-cell 120W charging.",
    image: "/assets/product-smartphone.png",
    badge: "New Arrival",
    featured: false,
    inStock: true,
    sku: "YMS-PHN-RMGT6",
    specs: ["12GB RAM / 256GB Storage", "Snapdragon 8s Gen 3 (4nm)", "6.78\" 8T LTPO AMOLED 120Hz", "50MP Triple Camera", "120W SuperVOOC Fast Charge"],
  },
  {
    slug: "realme-12-pro-plus-5g",
    name: "Realme 12 Pro+ 5G (8GB/256GB)",
    categorySlug: "smartphones",
    price: 42000,
    compareAtPrice: 45000,
    shortDescription: "Premium design featuring an iconic periscope portrait camera and luxury watch design.",
    description: "Stand out with a luxury-watch inspired design. The Realme 12 Pro+ features a dedicated 64MP Periscope Portrait Camera with 3x optical zoom and 120Hz curved display.",
    image: "/assets/product-smartphone.png",
    badge: "Curved Display",
    featured: false,
    inStock: true,
    sku: "YMS-PHN-RM12PP",
    specs: ["8GB RAM / 256GB Storage", "Snapdragon 7s Gen 2", "6.7\" Curved AMOLED 120Hz", "64MP Periscope + 50MP Sony IMX890", "67W charging Support"],
  },
  {
    slug: "infinix-note-40-pro-256gb",
    name: "Infinix Note 40 Pro (8GB/256GB)",
    categorySlug: "smartphones",
    price: 26500,
    compareAtPrice: 28500,
    shortDescription: "Budget-friendly performance with 70W fast charging and magnetic wireless charging.",
    description: "The Infinix Note 40 Pro brings premium charging capabilities to a budget price, including 70W Multi-Speed fast charge and MagCharge wireless support.",
    image: "/assets/product-smartphone.png",
    badge: "MagCharge Tech",
    featured: false,
    inStock: true,
    sku: "YMS-PHN-IFN40P",
    specs: ["8GB RAM / 256GB Storage", "Helio G99 Ultimate", "6.78\" 3D Curved AMOLED 120Hz", "108MP OIS Main Camera", "70W Wired / 20W Wireless Charging"],
  },

  // ── CATEGORY: AUDIO (10 Items) ──────────────────────────────
  {
    slug: "apple-airpods-pro-2-usbc",
    name: "Apple AirPods Pro (2nd Generation) USB-C",
    categorySlug: "audio",
    price: 24500,
    compareAtPrice: 27000,
    shortDescription: "Premium earbuds with Active Noise Cancellation, Adaptive Audio, and USB-C case.",
    description: "AirPods Pro (2nd generation) with USB-C deliver up to 2x more Active Noise Cancellation than the previous generation, with Transparency mode, Adaptive Audio, and Personalized Spatial Audio.",
    image: "https://images.unsplash.com/photo-1588449668365-d15e397f6787?q=80&w=600&auto=format&fit=crop",
    badge: "ANC King",
    featured: true,
    inStock: true,
    sku: "YMS-AUD-APAP2",
    specs: ["H2 Apple Silicon Chip", "Custom Active Noise Cancellation", "Adaptive Audio & Transparency mode", "MagSafe Charger Case (USB-C)", "Up to 6 hours listening time (single charge)"],
  },
  {
    slug: "samsung-galaxy-buds2-pro",
    name: "Samsung Galaxy Buds2 Pro",
    categorySlug: "audio",
    price: 16500,
    compareAtPrice: 18500,
    shortDescription: "Hi-Fi 24-bit audio earbuds with active noise cancellation and ergonomic fit.",
    description: "Experience absolute immersion. Samsung Galaxy Buds2 Pro deliver studio-quality sound with 24-bit Hi-Fi audio and intelligent Active Noise Cancellation.",
    image: "/assets/product-earbuds.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-AUD-SGB2P",
    specs: ["24-bit Hi-Fi audio quality", "Intelligent ANC & Ambient sound", "360 Audio support", "Ergonomic slim design", "IPX7 Water resistance"],
  },
  {
    slug: "sony-wf-1000xm5",
    name: "Sony WF-1000XM5 Wireless Earbuds",
    categorySlug: "audio",
    price: 27500,
    compareAtPrice: 30000,
    shortDescription: "Industry-leading noise canceling earbuds with high-res audio and premium microphones.",
    description: "The WF-1000XM5 features cutting-edge technology to deliver premium sound quality and the best noise-canceling performance on the market.",
    image: "/assets/product-earbuds.png",
    badge: "Audiophile Pick",
    featured: true,
    inStock: true,
    sku: "YMS-AUD-SNXM5",
    specs: ["Industry-leading Noise Canceling", "Integrated Processor V2 & QN2e", "High-Resolution Audio Wireless", "Precise Voice Pickup technology", "Up to 8 hours battery (24h with case)"],
  },
  {
    slug: "oneplus-buds-3",
    name: "OnePlus Buds 3",
    categorySlug: "audio",
    price: 7500,
    compareAtPrice: 8500,
    shortDescription: "Dual dynamic drivers, high-res audio certified, and 49dB active noise canceling.",
    description: "OnePlus Buds 3 features spectacular audio performance with dual drivers (10.4mm + 6mm), sliding volume controls, and adaptive noise cancellation.",
    image: "/assets/product-earbuds.png",
    badge: "Popular",
    featured: false,
    inStock: true,
    sku: "YMS-AUD-OPB3",
    specs: ["Dual Dynamic Drivers", "49dB Active Noise Cancellation", "Hi-Res Audio (LHDC 5.0)", "Up to 44 hours total playback", "Sliding Touch controls"],
  },
  {
    slug: "anker-soundcore-liberty-4-nc",
    name: "Anker Soundcore Liberty 4 NC",
    categorySlug: "audio",
    price: 8200,
    compareAtPrice: 9000,
    shortDescription: "Features 98.5% noise reduction, Hi-Res audio, and incredible 50-hour battery life.",
    description: "Reduce noise by up to 98.5% with Liberty 4 NC's high-performance adaptive ANC system. Enjoy crisp details with custom 11mm drivers and LDAC high-res audio.",
    image: "/assets/product-earbuds.png",
    badge: "Long Battery",
    featured: false,
    inStock: true,
    sku: "YMS-AUD-AKL4NC",
    specs: ["98.5% Noise Cancellation", "Hi-Res Audio Wireless & LDAC", "11mm Custom drivers", "Up to 10 hours playback (50h total)", "IPX4 water resistance"],
  },
  {
    slug: "oraimo-freepods-4",
    name: "Oraimo FreePods 4",
    categorySlug: "audio",
    price: 3400,
    compareAtPrice: 3800,
    shortDescription: "Value earbuds featuring active noise cancellation, heavy bass, and 35.5-hour playtime.",
    description: "Oraimo FreePods 4 provides high-quality sound with Pro Hybrid Active Noise Cancellation, low-latency game mode, and signature massive HavyBass sound.",
    image: "/assets/product-earbuds.png",
    badge: "Value King",
    featured: false,
    inStock: true,
    sku: "YMS-AUD-ORFP4",
    specs: ["Pro Hybrid ANC (Up to 30dB)", "Oraimo Sound App support", "HavyBass technology", "Up to 35.5 hours total battery", "Low-latency Game mode"],
  },
  {
    slug: "redmi-buds-5-pro",
    name: "Redmi Buds 5 Pro",
    categorySlug: "audio",
    price: 6200,
    compareAtPrice: 7000,
    shortDescription: "Dual-driver acoustic system with coaxial design, LDAC support, and 52dB active ANC.",
    description: "The Redmi Buds 5 Pro delivers impressive acoustics with a dual dynamic driver design, high-resolution LDAC encoding, and deep 52dB active noise cancellation.",
    image: "/assets/product-earbuds.png",
    badge: "New",
    featured: false,
    inStock: true,
    sku: "YMS-AUD-RMB5P",
    specs: ["Coaxial Dual Drivers (11mm+10mm)", "52dB Active Noise Cancellation", "Hi-Res Audio Wireless & LDAC", "Up to 38 hours battery with case", "3-mic setup with AI noise reduction"],
  },
  {
    slug: "realme-buds-air-5-pro",
    name: "Realme Buds Air 5 Pro",
    categorySlug: "audio",
    price: 7200,
    compareAtPrice: 8000,
    shortDescription: "Dual drivers, 50dB active noise cancellation, and high-res spatial audio.",
    description: "Experience theatrical sound. The Buds Air 5 Pro features a real coaxial dual driver system, deep ANC, and support for high-definition LDAC playback.",
    image: "/assets/product-earbuds.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-AUD-RBA5P",
    specs: ["Coaxial Dual Drivers", "50dB Active Noise Cancellation", "Hi-Res Audio certified with LDAC", "360-degree Spatial Audio", "Up to 40 hours playtime"],
  },
  {
    slug: "jbl-tune-230nc-tws",
    name: "JBL Tune 230NC TWS",
    categorySlug: "audio",
    price: 7800,
    compareAtPrice: 8800,
    shortDescription: "Wireless earbuds with JBL Pure Bass sound, active noise canceling, and 4-mic call technology.",
    description: "Tackle your day one song at a time. The JBL Tune 230NC TWS gives you 40 hours of exceptional JBL Pure Bass Sound, ANC, and water-resistant comfort.",
    image: "/assets/product-earbuds.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-AUD-JBL230",
    specs: ["JBL Pure Bass Sound", "Active Noise Cancelling with Smart Ambient", "4 Microphones for perfect calls", "Up to 40 hours battery life", "IPX4 Water & Sweat resistant"],
  },
  {
    slug: "xiaomi-portable-speaker-16w",
    name: "Xiaomi Portable Bluetooth Speaker (16W)",
    categorySlug: "audio",
    price: 3800,
    compareAtPrice: 4500,
    shortDescription: "High-quality 16W sound output, dual EQ modes, IPX7 water resistance, and TWS connection.",
    description: "Make music come alive. This speaker delivers powerful 16W audio, dual custom equalizer modes, IPX7 waterproof housing, and true wireless stereo pairing.",
    image: "/assets/product-earbuds.png",
    badge: "Waterproof",
    featured: false,
    inStock: true,
    sku: "YMS-AUD-XMSP16",
    specs: ["16W High Quality Sound", "IPX7 Waterproof body", "Dual EQ Modes (Normal & Deep Bass)", "True Wireless Stereo (TWS) pairing", "Up to 13 hours playtime"],
  },

  // ── CATEGORY: WEARABLES (10 Items) ──────────────────────────
  {
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2 (GPS + Cellular)",
    categorySlug: "wearables",
    price: 94500,
    compareAtPrice: 102000,
    shortDescription: "Ultimate sports watch with lightweight titanium case, dual-frequency GPS, and 3000 nits screen.",
    description: "The most rugged and capable Apple Watch ever, designed for endurance, exploration, and adventure. Featuring the S9 SiP chip, a double-tap gesture, and up to 36 hours of normal battery life.",
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?q=80&w=600&auto=format&fit=crop",
    badge: "Ultra Rugged",
    featured: true,
    inStock: true,
    sku: "YMS-WAT-AWU2",
    specs: ["49mm Titanium Case", "Always-On Retina display (3000 nits)", "S9 SiP with Double Tap gesture", "Precision Dual-frequency GPS", "Water resistant up to 100 meters"],
  },
  {
    slug: "apple-watch-series-9-gps",
    name: "Apple Watch Series 9 (GPS, 45mm)",
    categorySlug: "wearables",
    price: 44500,
    compareAtPrice: 48500,
    shortDescription: "Always-on Retina display, double tap gesture, advanced health tracking features.",
    description: "The Apple Watch Series 9 is smarter, brighter, and mightier. Powered by the S9 SiP chip, it features a magic way to use your watch without touching the screen.",
    image: "/assets/product-watch.png",
    badge: "Best Seller",
    featured: true,
    inStock: true,
    sku: "YMS-WAT-AWS9",
    specs: ["45mm Aluminium Case", "Always-On Retina display (2000 nits)", "ECG, Blood Oxygen & Heart Rate tracking", "Crash Detection & Fall Detection", "Double Tap gesture support"],
  },
  {
    slug: "samsung-galaxy-watch-6-44mm",
    name: "Samsung Galaxy Watch 6 (44mm)",
    categorySlug: "wearables",
    price: 26500,
    compareAtPrice: 29500,
    shortDescription: "Features a larger display, custom fitness coaching, and sleep analysis tools.",
    description: "Start your everyday wellness journey. The Galaxy Watch 6 features a refined circular dial with a slimmer bezel, detailed sleep coaching, and advanced heart health monitoring.",
    image: "/assets/product-watch.png",
    badge: "LTE Version",
    featured: false,
    inStock: true,
    sku: "YMS-WAT-SGW6",
    specs: ["44mm Armor Aluminum", "Super AMOLED Always-on screen", "Exynos W930 Dual-core", "Sleep Coaching & Body Composition analysis", "5ATM + IP68 rating"],
  },
  {
    slug: "oneplus-watch-2",
    name: "OnePlus Watch 2 (WearOS)",
    categorySlug: "wearables",
    price: 24500,
    compareAtPrice: 27000,
    shortDescription: "Dual-Engine architecture with Wear OS, up to 100-hour smart mode battery life.",
    description: "Your partner in time. The OnePlus Watch 2 delivers up to 100 hours of battery life in Smart Mode using Google Wear OS 4, and features high-precision dual-frequency GPS.",
    image: "/assets/product-watch.png",
    badge: "100h Battery",
    featured: false,
    inStock: true,
    sku: "YMS-WAT-OPW2",
    specs: ["Stainless Steel Case & Sapphire Crystal", "Dual-Engine (Snapdragon W5 + BES2700)", "Google Wear OS 4", "Dual-frequency L1+L5 GPS", "100-hour Battery in Smart Mode"],
  },
  {
    slug: "amazfit-gtr-4",
    name: "Amazfit GTR 4 Smartwatch",
    categorySlug: "wearables",
    price: 18200,
    compareAtPrice: 20000,
    shortDescription: "Classic watch design with dual-band GPS, 150+ sports modes, and 14-day battery life.",
    description: "The Amazfit GTR 4 features a classic metal casing, dual-band circular-polarized GPS antenna, real-time navigation tracking, and up to 14 days of battery life.",
    image: "/assets/product-watch.png",
    badge: "Classic Look",
    featured: false,
    inStock: true,
    sku: "YMS-WAT-AZGTR4",
    specs: ["1.43\" HD AMOLED display", "Dual-band Circularly Polarized GPS", "BioTracker 4.0 Health Sensor", "150+ Sports Modes & Strength exercise recognition", "14-day typical battery life"],
  },
  {
    slug: "xiaomi-watch-s3",
    name: "Xiaomi Watch S3 (Bezel Interchangable)",
    categorySlug: "wearables",
    price: 14500,
    compareAtPrice: 16500,
    shortDescription: "Runs Xiaomi HyperOS, features interchangeable bezels, and supports eSIM/Bluetooth calling.",
    description: "Upgrade your style with the Xiaomi Watch S3. Featuring an innovative interchangeable bezel design, customizable watch faces, and smooth HyperOS performance.",
    image: "/assets/product-watch.png",
    badge: "Unique Bezel",
    featured: false,
    inStock: true,
    sku: "YMS-WAT-XMS3",
    specs: ["1.43\" AMOLED display", "Interchangeable Bezel system", "Xiaomi HyperOS integration", "150+ sports modes & dual-band GNSS", "Up to 15 days battery life"],
  },
  {
    slug: "redmi-watch-4",
    name: "Redmi Watch 4",
    categorySlug: "wearables",
    price: 9200,
    compareAtPrice: 10500,
    shortDescription: "Large 1.97\" AMOLED display, aluminum alloy frame, and up to 20-day battery life.",
    description: "The Redmi Watch 4 features a premium aluminum chassis, a massive screen, bluetooth calling, and a long-lasting battery that is perfect for everyday use.",
    image: "/assets/product-watch.png",
    badge: "Big Screen",
    featured: true,
    inStock: true,
    sku: "YMS-WAT-RMW4",
    specs: ["1.97\" LTPS AMOLED 60Hz", "Aluminum Alloy middle frame", "Bluetooth Phone Calls support", "Four-system GNSS tracking", "Up to 20 days battery life"],
  },
  {
    slug: "kieslect-ks-pro",
    name: "Kieslect Ks Pro Smartwatch",
    categorySlug: "wearables",
    price: 6800,
    compareAtPrice: 7500,
    shortDescription: "Large 2.01\" AMOLED display, Bluetooth calling, and runs Kieslect OS.",
    description: "Kieslect Ks Pro features a massive screen, abnormal heart rate warning alerts, built-in voice assistants, and dynamic UI animations.",
    image: "/assets/product-watch.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-WAT-KLKSP",
    specs: ["2.01\" Ultra AMOLED display", "Stable Bluetooth Calling", "Abnormal Heart Rate Warning", "IP68 Waterproof rating", "Multiple watch strap bundles included"],
  },
  {
    slug: "colmi-c81-smartwatch",
    name: "Colmi C81 Smartwatch",
    categorySlug: "wearables",
    price: 3400,
    compareAtPrice: 4000,
    shortDescription: "Budget smartwatch featuring an AMOLED display and Bluetooth calling.",
    description: "Get high-end looks on a budget. The Colmi C81 features a bright AMOLED display, custom fitness dials, and hands-free calling capabilities.",
    image: "/assets/product-watch.png",
    badge: "Budget King",
    featured: false,
    inStock: true,
    sku: "YMS-WAT-CMC81",
    specs: ["2.0\" AMOLED Screen", "Always On Display mode", "Bluetooth Calling with built-in mic", "SpO2 & Heart Rate metrics", "Up to 7 days standby time"],
  },
  {
    slug: "huawei-band-9",
    name: "Huawei Band 9 Fitness Tracker",
    categorySlug: "wearables",
    price: 3900,
    compareAtPrice: 4500,
    shortDescription: "Slim design, scientific sleep monitoring, and up to 14 days of battery.",
    description: "Huawei Band 9 features a lightweight, skin-friendly strap, full-range health tracking (TruSleep 4.0), and water resistance up to 50 meters.",
    image: "/assets/product-watch.png",
    badge: "Slim Tracker",
    featured: false,
    inStock: true,
    sku: "YMS-WAT-HWB9",
    specs: ["1.47\" AMOLED rectangular screen", "9.99mm Ultra-thin profile", "Huawei TruSleep 4.0 sleep analytics", "100 workout modes", "Up to 14 days battery life"],
  },

  // ── CATEGORY: ACCESSORIES (10 Items) ────────────────────────
  {
    slug: "anker-nano-ii-65w-charger",
    name: "Anker Nano II 65W Fast Charger",
    categorySlug: "accessories",
    price: 3400,
    compareAtPrice: 3800,
    shortDescription: "Ultra-compact GaN fast charger for MacBooks, iPhones, and Android devices.",
    description: "Charge your laptops, tablets, and phones from a single tiny adapter. Anker Nano II uses GaN II technology to compress 65W of charging power into a pocketable footprint.",
    image: "/assets/product-laptop-tablet.png",
    badge: "GaN Charger",
    featured: true,
    inStock: true,
    sku: "YMS-ACC-AK65W",
    specs: ["65W USB-C PD Out", "GaN II Tech inside", "Folding Prongs design", "Over-voltage protection", "Compatible with PPS protocol"],
  },
  {
    slug: "samsung-25w-fast-charger",
    name: "Samsung 25W USB-C Power Adapter",
    categorySlug: "accessories",
    price: 1600,
    compareAtPrice: 1900,
    shortDescription: "Official Samsung 25W wall charger with Power Delivery (PD) PPS support.",
    description: "Get super fast charging for your Samsung Galaxy phones. Compatible with PPS charging to match your battery parameters for maximum longevity.",
    image: "/assets/product-smartphone.png",
    badge: "Official",
    featured: false,
    inStock: true,
    sku: "YMS-ACC-SS25W",
    specs: ["25W USB-C Output", "Super Fast Charging capability", "Power Delivery 3.0 PPS", "Short-circuit protection", "Compact travel adapter"],
  },
  {
    slug: "apple-20w-usbc-power-adapter",
    name: "Apple 20W USB-C Power Adapter",
    categorySlug: "accessories",
    price: 2400,
    compareAtPrice: 2800,
    shortDescription: "Original Apple 20W power adapter for fast charging iPhone 12 to 15 series.",
    description: "The Apple 20W USB-C Power Adapter offers fast, efficient charging at home, in the office, or on the go. Pair it with iPhone 8 or later for fast charging.",
    image: "/assets/product-smartphone.png",
    badge: "Official",
    featured: false,
    inStock: true,
    sku: "YMS-ACC-AP20W",
    specs: ["20W USB-C Output", "Original Apple Product", "Compact white finish", "Fast charging support for iOS", "Reliable voltage regulation"],
  },
  {
    slug: "baseus-blade-100w-powerbank",
    name: "Baseus Blade 100W 20000mAh Power Bank",
    categorySlug: "accessories",
    price: 5800,
    compareAtPrice: 6500,
    shortDescription: "Ultra-thin laptop power bank with status display and quad ports.",
    description: "The Baseus Blade features a slim 18mm form factor, 100W massive output, digital screen displaying charging time, power level, and current parameters.",
    image: "/assets/product-laptop-tablet.png",
    badge: "100W Laptop Power",
    featured: true,
    inStock: true,
    sku: "YMS-ACC-BSBL100",
    specs: ["20000mAh capacity", "100W Power Delivery output", "Dual USB-C & Dual USB-A ports", "Digital status display screen", "Ultra-thin laptop friendly design"],
  },
  {
    slug: "spigen-liquid-air-iphone-15-pm",
    name: "Spigen Liquid Air Case for iPhone 15 Pro Max",
    categorySlug: "accessories",
    price: 1800,
    compareAtPrice: 2200,
    shortDescription: "Premium protective case with signature geometric pattern and drop protection.",
    description: "Protect your flagship in style. The Spigen Liquid Air case features Air Cushion Technology for daily drop protection and a non-slip geometric texture.",
    image: "/assets/product-smartphone.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-ACC-SPLQ15PM",
    specs: ["Signature matte geometric design", "Air Cushion drop defense tech", "Raised bezels for screen/camera defense", "Tactile clicky buttons", "Wireless charging compatible"],
  },
  {
    slug: "baseus-cafule-3-in-1-cable",
    name: "Baseus Cafule 3-in-1 USB Cable (1.2m)",
    categorySlug: "accessories",
    price: 750,
    compareAtPrice: 950,
    shortDescription: "Durable braided cable splitting into Lightning, Type-C, and Micro USB outputs.",
    description: "One cable to charge them all. High-quality braided nylon Cafule 3-in-1 cable supports charging up to 3A total current for maximum convenience.",
    image: "/assets/product-smartphone.png",
    badge: "Durable",
    featured: false,
    inStock: true,
    sku: "YMS-ACC-BSCF31",
    specs: ["Type-C, Lightning & Micro-USB outputs", "Braided high-density nylon build", "Aluminum alloy connectors", "1.2 meters total length", "3A maximum current rating"],
  },
  {
    slug: "ugreen-6-in-1-usbc-hub",
    name: "Ugreen 6-in-1 USB-C Multi-port Hub",
    categorySlug: "accessories",
    price: 2800,
    compareAtPrice: 3200,
    shortDescription: "Expands your laptop's USB-C port with HDMI, SD/TF card slots, and USB-A ports.",
    description: "Expand your productivity. This aluminum adapter extends a single USB-C port with 4K HDMI, SD/TF readers, and three high-speed USB-A 3.0 ports.",
    image: "/assets/product-laptop-tablet.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-ACC-UG61HB",
    specs: ["4K@30Hz HDMI video out", "3x USB-A 3.0 (5Gbps) ports", "SD & Micro SD card reader slots", "Sleek Aluminum Shell", "Plug & Play system compatibility"],
  },
  {
    slug: "anker-powerline-iii-usbc-lightning",
    name: "Anker PowerLine III USB-C to Lightning (3ft)",
    categorySlug: "accessories",
    price: 1400,
    compareAtPrice: 1700,
    shortDescription: "Ultra-strong MFi certified charging cable with a lifespan of 25,000 bends.",
    description: "Upgrade your charging reliability. Anker PowerLine III features premium copper cores, dirt-resistant coating, and official MFi certification.",
    image: "/assets/product-smartphone.png",
    badge: "MFi Certified",
    featured: false,
    inStock: true,
    sku: "YMS-ACC-AKPL3CL",
    specs: ["USB-C to Lightning connector type", "MFi certified for iOS devices", "25,000 bend lifespan rating", "Easy-clean outer texture", "Supports Power Delivery fast charge"],
  },
  {
    slug: "oraimo-toast-10-byte-powerbank",
    name: "Oraimo Toast 10 Byte 10000mAh Power Bank",
    categorySlug: "accessories",
    price: 1500,
    compareAtPrice: 1800,
    shortDescription: "Super-slim design, dual output ports, and multi-protection safety system.",
    description: "Oraimo Toast 10 Byte fits comfortably in your pocket, providing 10,000mAh backup capacity, dual charging outputs, and texture-grip shell.",
    image: "/assets/product-smartphone.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-ACC-ORT10B",
    specs: ["10000mAh lithium battery", "Dual USB-A outputs", "Type-C & Micro-USB recharge inputs", "Multi-protect safety hardware", "Texture grip casing"],
  },
  {
    slug: "spigen-ultra-hybrid-s24-ultra",
    name: "Spigen Ultra Hybrid Case for Galaxy S24 Ultra",
    categorySlug: "accessories",
    price: 2200,
    compareAtPrice: 2600,
    shortDescription: "Crystal-clear hybrid casing that showcases your phone's original titanium design.",
    description: "Show off your Galaxy S24 Ultra. Spigen Ultra Hybrid features a clear polycarbonate back panel fused to a flexible TPU bumper.",
    image: "/assets/product-smartphone.png",
    badge: "Clear Shell",
    featured: false,
    inStock: true,
    sku: "YMS-ACC-SPUH24U",
    specs: ["Crystal clear transparent back", "Shock-absorbent TPU bumper border", "Pronounced tactile button covers", "Raised borders protect lens & screen", "Wireless charging & S Pen friendly"],
  },

  // ── CATEGORY: SMART HOME (5 Items) ──────────────────────────
  {
    slug: "xiaomi-air-purifier-4-compact",
    name: "Xiaomi Smart Air Purifier 4 Compact",
    categorySlug: "smart-home",
    price: 9500,
    compareAtPrice: 11000,
    shortDescription: "Compact smart air purifier with 3-in-1 filtration system and real-time PM2.5 tracking.",
    description: "Clean, fresh air on demand. Xiaomi Air Purifier 4 Compact is perfect for bedrooms or offices, offering high-efficiency filtration, quiet sleep mode, and smart app integration.",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=600&auto=format&fit=crop",
    badge: "Fresh Air",
    featured: true,
    inStock: true,
    sku: "YMS-SMT-XMAP4C",
    specs: ["3-in-1 HEPA Filtration", "Smart App control via Mi Home", "Quiet 20dB sleep noise level", "CADR rate 230m³/h", "PM2.5 particle tracking display"],
  },
  {
    slug: "google-nest-mini-2nd-gen",
    name: "Google Nest Mini (2nd Generation)",
    categorySlug: "smart-home",
    price: 3800,
    compareAtPrice: 4500,
    shortDescription: "Google Assistant smart speaker with improved bass response and wall mount.",
    description: "Meet the 2nd generation Nest Mini. The speaker delivers richer sound with 2x stronger bass and features built-in Google Assistant for voice-activated search and smart controls.",
    image: "/assets/product-earbuds.png",
    badge: null,
    featured: false,
    inStock: true,
    sku: "YMS-SMT-GGNM2",
    specs: ["Google Assistant integrated", "360-degree sound with 40mm driver", "3 Far-field microphones", "Eco-friendly fabric top material", "Wi-Fi & Bluetooth streaming support"],
  },
  {
    slug: "xiaomi-home-camera-2k",
    name: "Xiaomi Mi 360° Home Security Camera 2K",
    categorySlug: "smart-home",
    price: 4200,
    compareAtPrice: 4800,
    shortDescription: "2K ultra-clear image quality security camera with infrared night vision and AI detection.",
    description: "Monitor your home with peace of mind. Xiaomi Security Camera 2K features 360-degree pan-tilt-zoom, 1296p HD lens, advanced infrared night vision, and two-way talk.",
    image: "/assets/product-smartphone.png",
    badge: "360° Monitor",
    featured: true,
    inStock: true,
    sku: "YMS-SMT-XMC2K",
    specs: ["3MP camera lens / 2K 1296p video resolution", "360° horizontal / 108° vertical view rotation", "AI Human detection & movement alerts", "Infrared night vision sensors", "Two-way voice calls support"],
  },
  {
    slug: "tplink-tapo-smart-bulb",
    name: "TP-Link Tapo Smart Wi-Fi Light Bulb",
    categorySlug: "smart-home",
    price: 1100,
    compareAtPrice: 1350,
    shortDescription: "Multicolor smart bulb with Wi-Fi control, voice control, and scheduling options.",
    description: "Set the mood. The Tapo Multicolor Smart Bulb lets you choose from 16 million colors, save presets, set timers, and control your lights with Google Assistant or Alexa.",
    image: "/assets/product-smartphone.png",
    badge: "16M Colors",
    featured: false,
    inStock: true,
    sku: "YMS-SMT-TPTB1",
    specs: ["No Hub required (connects directly to 2.4G Wi-Fi)", "RGB multicolor + Warm to Cool white tuning", "Schedule & Timer setup via Tapo App", "Dimmable brightness control", "8.7W LED (equivalent to 60W bulb)"],
  },
  {
    slug: "xiaomi-tv-stick-4k",
    name: "Xiaomi TV Stick 4K Streaming Device",
    categorySlug: "smart-home",
    price: 5200,
    compareAtPrice: 5900,
    shortDescription: "Portable 4K streaming device running Android TV 11, with Dolby Atmos & Vision.",
    description: "Turn your standard television into a Smart TV. The Xiaomi TV Stick 4K connects to HDMI, providing smooth Android TV 11 access, Netflix/YouTube apps, and built-in Chromecast.",
    image: "/assets/product-laptop-tablet.png",
    badge: "4K Stream",
    featured: false,
    inStock: true,
    sku: "YMS-SMT-XMTS4K",
    specs: ["4K (3840 x 2160) video output", "Android TV 11 operating system", "Dolby Atmos & Dolby Vision support", "2GB RAM + 8GB Storage", "Bluetooth remote with Google Assistant mic"],
  },
];

async function seed() {
  console.log("Connecting to MongoDB Atlas...");
  await connectToDatabase();
  console.log("Connected to MongoDB.");

  // Clear existing categories and products to prevent duplicates
  console.log("Clearing existing Category and Product databases...");
  await Category.deleteMany({});
  await Product.deleteMany({});
  console.log("Databases successfully cleared.");

  // Seed Categories
  console.log("Seeding 5 Categories...");
  const categoryMap = new Map();
  for (const catSeed of categorySeeds) {
    const newCat = await Category.create({
      slug: catSeed.slug,
      name: catSeed.name,
      description: catSeed.description,
      sortOrder: catSeed.sortOrder,
    });
    categoryMap.set(catSeed.slug, newCat._id);
    console.log(`- Seeded category: ${newCat.name} (${newCat._id})`);
  }

  // Seed Products
  console.log(`Seeding ${productSeeds.length} Products...`);
  for (const prodSeed of productSeeds) {
    const categoryId = categoryMap.get(prodSeed.categorySlug);
    if (!categoryId) {
      console.warn(`Category slug '${prodSeed.categorySlug}' not found. Skipping product '${prodSeed.name}'.`);
      continue;
    }

    const newProd = await Product.create({
      slug: prodSeed.slug,
      name: prodSeed.name,
      categoryId: categoryId,
      price: prodSeed.price,
      compareAtPrice: prodSeed.compareAtPrice,
      shortDescription: prodSeed.shortDescription,
      description: prodSeed.description,
      image: prodSeed.image,
      badge: prodSeed.badge,
      featured: prodSeed.featured,
      inStock: prodSeed.inStock,
      sku: prodSeed.sku,
      specs: prodSeed.specs,
    });
    console.log(`- Seeded product: ${newProd.name} [SKU: ${newProd.sku}]`);
  }

  console.log("Database successfully seeded with 5 categories and 50 premium items!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Critical error during database seeding:", err);
  process.exit(1);
});
